### ISSUE TITLE
Short-circuit evaluation

### ISSUE THREAD

**Issue by aathn** [miking-lang/miking#136]
Currently, MCore does not have short-circuit evaluation for the boolean operators `and` and `or`, which is standard in most programming languages.

For instance, consider the following piece of code.

```ocaml
and false (let _ = printLn "hej" in true)
```

The code evaluates to `false` as expected, but it also prints `hej`, since both arguments to `and` are evaluated regardless of the fact that the first argument evaluates to `false`.

Short-circuiting would be nice to have, but would require treating `and` and `or` differently from the other intrinsics. Is it worth it, what do you think?

**Comment by johnwikman** [comment]
I suspect that we brought this up during a meeting after you made this issue, but never referenced this issue. IIRC the conclusion was that we do not want to have unneccesary special cases that deviates from the standard way of evaluation. As we are still just an IR, a higher-level language could implement `&&` as
```ml
a && b := if a then b else false
```

**Comment by aathn** [comment]
On the contrary, I opened this issue after that meeting, at the request of David, because the conclusion was not that clear-cut. (Or maybe I missed some very recent discussion?)

**Comment by johnwikman** [comment]
You did probably not miss a discussion, most likely I who forgot the conclusions of that meeting :slightly_smiling_face:

I am personally a bit torn on this. Because what is the purpose of having `and` and `or` instrinsics if they do not provide short-circuit evaluation? On the other hand, why introduce special cases in an IR for application when the desired behavior can be implemented using a short `if ... then ... else true/false`. What is there to gain for having the `and` and `or` intrinsics except for shorter (and perhaps cleaner) code?

**Comment by johnwikman** [comment]
I think that my conclusion would be to remove `and` and `or` as intrinsics. Instead implement them in `prelude.mc` as regular functions.

**Comment by elegios** [comment]
We discussed this at the meeting today and essentially came to the same conclusion as @johnwikman above: make `and` and `or` into functions in the prelude instead of intrinsics.

The potential drawback of this is recognizing compilation opportunities; most target languages support short-circuiting and/or builtins for `and` and `or`. The backends compiling to these targets would thus have to redisover these opportunities, and it would be nice to share this work between them.

The thought presented at the meeting was that we can have the following structure:
- We have mexpr proper, which is the small language we generally talk about. It has few intrinsics, and is the language most transformations and operations operate upon.
- We have a set of extension languages on top that rediscover these constructs. For example, one fragment could be something like this:

```
lang ShortCircuitAnd = MExpr
  syn Expr =
  | TmShortBoolAnd {l: Expr, r: Expr}

  sem resugar: MExpr.Expr -> Expr =
  | TmIf {cond = c, then = t, else = TmFalse _} = TmShortBoolAnd { l = c, r = t }
end
```

Backends would then compile not from `MExpr` directly but instead from `MExpr + ShorCiruitAnd` (or similar), after running `resugar`. We would thus share the work of rediscovering normal features (some of which may be more complicated to rediscover than this) and the final compilation step could potentially be a very simple lowering from a richer AST.

**Comment by david-broman** [comment]
I would like to discuss this again. I agree with the above that short circuit is important, but the main challenge is to rediscover, as also discussed above. I am not sure I like the idea of having different variants of MCore. I am afraid that this will become quite complex in the end. On the other hand, I think that we need to develop a method where standard library functions (especially in the prelude) can be pattern matched on directly in the compiler, thus treating them as intrinsics, even if they are implemented in the standard library (i.e. the semantics need to be preserved). That is, the compiler can use another implementation (not as in the standard library), as long as it follows the same semantics.

**Comment by johnwikman** [comment]
> I would like to discuss this again. I agree with the above that short circuit is important, but the main challenge is to rediscover, as also discussed above. I am not sure I like the idea of having different variants of MCore. I am afraid that this will become quite complex in the end. On the other hand, I think that we need to develop a method where standard library functions (especially in the prelude) can be pattern matched on directly in the compiler, thus treating them as intrinsics, even if they are implemented in the standard library (i.e. the semantics need to be preserved). That is, the compiler can use another implementation (not as in the standard library), as long as it follows the same semantics.

I see the resugaring of specific patterns as being a feature you enable in the compiler to aid code generation for a specific backend. It would not be a different variant of MCore, but more a set of compiler options (tailored to a target language) in my view.

**Comment by aathn** [comment]
Since the main purpose of this issue was to discuss whether we want short-circuiting boolean intrinsics in MCore, and the conclusion is that we don't, I'll go ahead and close this issue. As we discussed on the meeting today, we should probably open a brand new issue to discuss how to best rediscover opportunities for short-circuiting and so on.
