### ISSUE TITLE
Add stack trace debugging to boot

### ISSUE THREAD

**Issue by dlunde** [miking-lang/miking#174]
I think it would be great to have a debug option in boot to print a stack trace upon crashing, especially now before we have a type system. We can use this issue to discuss how this could be implemented.

**Comment by johnwikman** [comment]
I think that a stack trace would be nice to have. For me it is important to make such a stack trace reflects the written code, not the result of many AST transformations. E.g. if there is something wrong in an MLang fragment, I want to be referred to that language fragment, not to a convoluted match expression. Also, if a function gets split into multiple smaller functions during a transformation, I would like to just see the original function calls in the stack trace, hiding the function calls of the generated functions. This of course assumes that the transformations are correct and that no error is due to a transformation.
