### ISSUE TITLE
Bikeshedding: TODO comments and the like

### ISSUE THREAD

**Issue by elegios** [miking-lang/miking#181]
During the meeting today we discussed having a convention for TODOs and the like present in the code, adding names, and/or dates to them. This issue is to discuss those conventions, and also what our general policy should be on leaving TODOs in the code vs fixing things immediately.

I would propose the following style:
```
-- TODO(vipa, 2020-09-17): this is something that should be done. These should not live
-- for a very long time

-- NOTE(vipa, 2020-09-17): this is something that might be surprising about the code,
-- something about why things are done the way they are. These likely live for a long time.

-- OPT(vipa, 2020-09-17): this is a likely place for optimization down the line. These may
-- well live for a while.
```

Out of those three I'm the least decided on the one about optimization. I feel like it's decently often that we know that something is inefficient, but it's not an issue yet (I'm also not sure `OPT` is descriptive enough, maybe it should just as well be `OPTIMIZE`, or `PERFORMANCE`). We have some TODOs right now that are possible optimizations.

The date can be useful as a quick indicator of how relevant the comment is, if it might have been invalidated since then. There are also tools that can extract the dates and do things automatically, e.g., fail a commit if a comment has gotten too old or something, to increase the probability of comments being up-to-date. Adding dates means that we could do these things should we want to.

-------------------------------

On policy, at the time of writing some quick `ag`ing suggests that we have 63 TODOs in the project right now. Some of them are known things that we're intentionally not doing yet, e.g., things that require a proper FFI, or more fancy mlang features. Others are things we've merely not taken the time to do, e.g., escaping characters properly in `pprint.mc`, or add tests that use alpha-equivalence (and implement a check for alpha-equivalence of course).

I think we're all in agreement that in an ideal world we wouldn't leave any TODOs at all in the codebase, but I don't think that's quite doable without just ignoring things.

Here are a few thoughts on things we could do, in no particular order, and without me really championing them, just listing them for discussion.

1. Fail commits/PRs if they contain TODOs above some age. This gives essentially random failures which doesn't seem nice, but it does encourage fixing things, if a bit heavy-handedly.
1. Have a bot that posts a delta of number of TODOs for a PR, to make us aware of when these things change.
1. Mandate that each TODO in a merged PR should have an associated issue (possibly multiple TODOs per issue, no need to be overly pedantic). I think it should be possible to automate a lot of this, make a github action that creates issues from TODOs and makes a commit that attaches the issue number to the comment, that kind of thing. It might exist, so we might not have to create it ourselves. Doing it manually is of course also an option.

Now for my opinions on these: I kinda like 2 as a nice sanity check. 1 feels too harsh and more importantly places the burden on the wrong person. 3 might be nice in that it becomes a more concrete "this needs to be done", but I'm not sure if it's actually desirable to be super strict about it. I can imagine having some such issues that are assigned to particular people, things that live in research projects (decision points, autodiff, etc.), and some that are tagged "chores" or something like it, things that need to be done but aren't as clearly something to be done by a particular person. The amount of admin is likely important here, if it's too much work it's not a good solution, either because it won't be done, or because it takes too much time from actual work.

**Comment by johnwikman** [comment]
Regarding the style, I feel like the parenthesis can probably be dropped.
```
-- TODO johnwikman 2020-09-17: Without the parenthesis looks fairly OK as well, but
-- may start to look wierd when spanning multiple lines?

-- TODO johnwikman 2020-09-17:
-- Or just make the comment on what needs to be done
-- start on the line after the "metadata".
```
Also, I am a bit confused regarding having a date for `NOTE`. What is the date used for here?

**Comment by elegios** [comment]
Most information ages, and it's remarkably easy to miss updating a related comment when what it describes is changed. Adding a date gives some information when trying to figure out to what extent the comment is up to date.

**Comment by EliasC** [comment]
Since we're bikeshedding, I very much prefer the parentheses since it clearly delimits the different parts of the comment:
```
-- TODO(This is who wrote it, and when): This is the description
```
I think it makes sense to be fairly strict regarding the style here, especially if we want to start extracting information from them (not saying that my style is better, just that we should be consistent). 

Regarding policy I don't think it makes sense to punish later committers for old TODOs. I think having a bot posting deltas is a very good idea as a reminder that we should be looking at these things. Regarding issues, I am for encouraging duplicating TODOs as issues when applicable, but I don't think that we should try to automate it just yet. If we want to start assigning TODOs to people, then using issues is probably the way to go. I could imagine having a list of all the TODOs together with their assignees, but it feels like keeping this list in sync is going to become tedious very quickly. On the other hand, it would be very nice with that kind of overview! Not sure what the best way forward is here...

Does it make sense to go through all the TODOs in the repo and mark them with contributor and commit time (this should be a safe approximation I think), once we have decided on a style?
