### ISSUE TITLE
Include cycle when running boot test from root directory

### ISSUE THREAD

**Issue by br4sco** [miking-lang/miking#35]
When I run `../build/boot test seq.mc` from the folder `stdlib` the unit tests in `seq.mc` are executed as expected. However, when I try to run the same tests from the root directory `./build/boot test stdlib/seq.mc` I get an include cycle error.

Below is an the shell output showing this behavior 

```
(base) oerikss@bit:~/rps/miking$ echo $MCORE_STDLIB
/home/oerikss/rps/miking/stdlib
(base) oerikss@bit:~/rps/miking$ ./build/boot test stdlib/seq.mc 
stdlib/seq.mc: 
FILE "stdlib/prelude.mc" 2:0-2:16 ERROR: Cycle detected in included files: stdlib/seq.mc
ERROR! 0 successful tests and 1 failed tests.

(base) oerikss@bit:~/rps/miking$ cd stdlib/
(base) oerikss@bit:~/rps/miking/stdlib$ ../build/boot test seq.mc
seq.mc: ............................. OK
Unit testing SUCCESSFUL after executing 29 tests.
```

**Comment by elegios** [comment]
I believe this is the auto-include of the prelude, since `prelude.mc` includes `seq.mc`, but I don't quite see why it wouldn't trigger when running inside stdlib. `make test` will run tests on `stdlib` by explicitly unsetting `$MCORE_STDLIB`, which disables the auto-include.

**Comment by EliasC** [comment]
It seems like we should be able to detect this after the fixes in #65 and avoid the duplicate inclusion, but maybe it's more work than it's worth for a feature that is going to need revamping at some point anyway?

**Comment by elegios** [comment]
We would unfortunately not, the problem is that the program we point `boot` at implicitly includes the prelude. In this case we're pointing it at `stdlib/seq.mc`, but `prelude.mc` includes that file, thus we have a cycle.

We could change the method by which we include prelude, maybe parse it first and add the definitions instead of having that happen via the include feature, or add some way to state that a program should not include the prelude ( `{-# LANGUAGE NoImplicitPrelude #-}` in Haskell).

Separate thought that I did not consider until now: includes as they are now are fundamentally side-effects, in the sense that multiple definitions of the same name in different files may shadow each other differently depending on how the include graph happens to end up.

**Comment by EliasC** [comment]
I mean that we should be able to special-case the files that live in the standard library (and that this could be properly detected by normalizing file paths). Or maybe it only concerns the files included by the prelude? Either way, the current solution of using `"@@@"` as a magic string in the compiler and the makefile is a real eyesore...

> includes as they are now are fundamentally side-effects, in the sense that multiple definitions of the same name in different files may shadow each other differently depending on how the include graph happens to end up.

That is very much the case, and one of the reasons we shouldn't spend too much time making the file-inclusion implementation too ergonomic :)
