### ISSUE TITLE
Create miking main command "mi". Discission: "mi compile" and "mi debug" or "mic" and "mid" etc.

### ISSUE THREAD

**Issue by david-broman** [miking-lang/miking#97]

**Comment by johnwikman** [comment]
I would prefer a mixture of both. Having the `mi compile` and `mi evaluate` is nice since it avoids cluttering the PATH, potentially avoiding collisions with other three-character programs that might be installed on the system. At the same time I think that it is easy to provide a shorthand solution to easily run programs. For example, if I have written a small "throw-away" test program called `test.ml`, I would like to evaluate it by just typing `mi test.ml`. It makes a difference in my opinion.

Another alternative could be that you specify actions through option parameters. Instead of writing `mi compile test.ml` or `mi evaluate test.ml`, one could instead write `mi --compile test.ml` or `mi --evaluate test.ml` where `--evaluate` is the default option. Could also be nice to have `-c`and `-e` shorthand versions of the options above.

**Comment by dlunde** [comment]
I like git-style commands (`mi compile` and `mi evaluate`).

**Comment by EliasC** [comment]
During today's meeting, we considered this issue resolved!
